<?php

namespace Database\Seeders;

use App\Models\Customer;
use App\Models\Person;
use App\Models\Telephone;
use Illuminate\Support\Str;
use Illuminate\Database\Seeder;

class CustomerChavezCallaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $persona1=Person::create(['ci'=>' ','name'=>'COMERCIAL MENDOZA','address' => 'B/LA LOMA C/ SAN JUAN ANTES DE KA CALLE VENEZUELA, AL LADO DEL JARDIN']);	$cliente1=Customer::create(['person_id'=>$persona1->id, 'slug'=>Str::uuid(),'description'=>'EFRAEN MENDOZA MORALES','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona1->id,'number'=>'68769406','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona1->id,'number'=>'63793154','type'=>'SECONDARY']);
        $persona2=Person::create(['ci'=>' ','name'=>'OMAR VARGAS','address' => 'CALLE SAN JUAN A 15 METROS DE LA CALLE CORAZON DE JESUS']);	$cliente2=Customer::create(['person_id'=>$persona2->id, 'slug'=>Str::uuid(),'description'=>'TODO BAÑO IMPORTACIONES','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona2->id,'number'=>'69311244','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona2->id,'number'=>'71861281','type'=>'SECONDARY']);
        $persona3=Person::create(['ci'=>' ','name'=>'','address' => 'C/ VENEZUELA Y C/ CORAZON DE JESUS']);	$cliente3=Customer::create(['person_id'=>$persona3->id, 'slug'=>Str::uuid(),'description'=>'DAMSER S.R.L.','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona3->id,'number'=>'73480877','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona3->id,'number'=>'72971360','type'=>'SECONDARY']);
        $persona4=Person::create(['ci'=>' ','name'=>'JANETH GARZON','address' => '']);	$cliente4=Customer::create(['person_id'=>$persona4->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona4->id,'number'=>'71862223','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona4->id,'number'=>'','type'=>'SECONDARY']);
        $persona5=Person::create(['ci'=>' ','name'=>'MONICA CASTELLANOS','address' => '']);	$cliente5=Customer::create(['person_id'=>$persona5->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona5->id,'number'=>'70234368','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona5->id,'number'=>'','type'=>'SECONDARY']);
        $persona6=Person::create(['ci'=>' ','name'=>'ERICK TORREZ','address' => '']);	$cliente6=Customer::create(['person_id'=>$persona6->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona6->id,'number'=>'74826189','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona6->id,'number'=>'','type'=>'SECONDARY']);
        $persona7=Person::create(['ci'=>' ','name'=>'REYNOLD SIGLER','address' => '']);	$cliente7=Customer::create(['person_id'=>$persona7->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona7->id,'number'=>'72974235','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona7->id,'number'=>'','type'=>'SECONDARY']);
        $persona8=Person::create(['ci'=>' ','name'=>'CLAUDIA GALINDO','address' => '']);	$cliente8=Customer::create(['person_id'=>$persona8->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona8->id,'number'=>'71864417','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona8->id,'number'=>'','type'=>'SECONDARY']);
        $persona9=Person::create(['ci'=>' ','name'=>'SERGIO LIZARRAGA','address' => '']);	$cliente9=Customer::create(['person_id'=>$persona9->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona9->id,'number'=>'70219214','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona9->id,'number'=>'','type'=>'SECONDARY']);
        $persona10=Person::create(['ci'=>' ','name'=>'ANTONIO SANCHEZ','address' => '']);	$cliente10=Customer::create(['person_id'=>$persona10->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona10->id,'number'=>'73312644','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona10->id,'number'=>'','type'=>'SECONDARY']);
        $persona11=Person::create(['ci'=>' ','name'=>'PAUL VASQUEZ','address' => '']);	$cliente11=Customer::create(['person_id'=>$persona11->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona11->id,'number'=>'71864656','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona11->id,'number'=>'','type'=>'SECONDARY']);
        $persona12=Person::create(['ci'=>' ','name'=>'ROSARIO MENDOZA','address' => '']);	$cliente12=Customer::create(['person_id'=>$persona12->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona12->id,'number'=>'72978733','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona12->id,'number'=>'','type'=>'SECONDARY']);
        $persona13=Person::create(['ci'=>' ','name'=>'MARCO GARCIA','address' => '']);	$cliente13=Customer::create(['person_id'=>$persona13->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona13->id,'number'=>'67220224','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona13->id,'number'=>'','type'=>'SECONDARY']);
        $persona14=Person::create(['ci'=>' ','name'=>'PEDRO ARAMAYO','address' => '']);	$cliente14=Customer::create(['person_id'=>$persona14->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona14->id,'number'=>'72946864','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona14->id,'number'=>'','type'=>'SECONDARY']);
        $persona15=Person::create(['ci'=>' ','name'=>'DAVID RIVERA','address' => '']);	$cliente15=Customer::create(['person_id'=>$persona15->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona15->id,'number'=>'70213806','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona15->id,'number'=>'','type'=>'SECONDARY']);
        $persona16=Person::create(['ci'=>' ','name'=>'SAMUEL OVANDO','address' => '']);	$cliente16=Customer::create(['person_id'=>$persona16->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona16->id,'number'=>'67379325','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona16->id,'number'=>'','type'=>'SECONDARY']);
        $persona17=Person::create(['ci'=>' ','name'=>'DANIELA','address' => '']);	$cliente17=Customer::create(['person_id'=>$persona17->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona17->id,'number'=>'72998000','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona17->id,'number'=>'','type'=>'SECONDARY']);
        $persona18=Person::create(['ci'=>' ','name'=>'WILFREDO SALINAS','address' => '']);	$cliente18=Customer::create(['person_id'=>$persona18->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona18->id,'number'=>'76204144','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona18->id,'number'=>'','type'=>'SECONDARY']);
        $persona19=Person::create(['ci'=>' ','name'=>'LUIS ALBERTO CASTELLON','address' => '']);	$cliente19=Customer::create(['person_id'=>$persona19->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona19->id,'number'=>'77177977','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona19->id,'number'=>'','type'=>'SECONDARY']);
        $persona20=Person::create(['ci'=>' ','name'=>'PABLO ORTIZ','address' => '']);	$cliente20=Customer::create(['person_id'=>$persona20->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona20->id,'number'=>'78223345','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona20->id,'number'=>'','type'=>'SECONDARY']);
        $persona21=Person::create(['ci'=>' ','name'=>'CLAUDIA URRIOLAGOITIA','address' => '']);	$cliente21=Customer::create(['person_id'=>$persona21->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona21->id,'number'=>'70210707','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona21->id,'number'=>'','type'=>'SECONDARY']);
        $persona22=Person::create(['ci'=>' ','name'=>'BENITO FERNANDEZ','address' => '']);	$cliente22=Customer::create(['person_id'=>$persona22->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona22->id,'number'=>'61874016','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona22->id,'number'=>'','type'=>'SECONDARY']);
        $persona23=Person::create(['ci'=>' ','name'=>'KATIA ESCALANTE','address' => '']);	$cliente23=Customer::create(['person_id'=>$persona23->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona23->id,'number'=>'75133157','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona23->id,'number'=>'','type'=>'SECONDARY']);
        $persona24=Person::create(['ci'=>' ','name'=>'CARMEN VARGAS','address' => '']);	$cliente24=Customer::create(['person_id'=>$persona24->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona24->id,'number'=>'72957026','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona24->id,'number'=>'','type'=>'SECONDARY']);
        $persona25=Person::create(['ci'=>' ','name'=>'MILTON JIJENAR','address' => '']);	$cliente25=Customer::create(['person_id'=>$persona25->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona25->id,'number'=>'72944676','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona25->id,'number'=>'','type'=>'SECONDARY']);
        $persona26=Person::create(['ci'=>' ','name'=>'DEIMAR FITA','address' => '']);	$cliente26=Customer::create(['person_id'=>$persona26->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona26->id,'number'=>'77474115','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona26->id,'number'=>'','type'=>'SECONDARY']);
        $persona27=Person::create(['ci'=>' ','name'=>'ING GUDIÑO','address' => '']);	$cliente27=Customer::create(['person_id'=>$persona27->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona27->id,'number'=>'77875004','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona27->id,'number'=>'','type'=>'SECONDARY']);
        $persona28=Person::create(['ci'=>' ','name'=>'FRANKLIN VERA','address' => '']);	$cliente28=Customer::create(['person_id'=>$persona28->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona28->id,'number'=>'72963317','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona28->id,'number'=>'','type'=>'SECONDARY']);
        $persona29=Person::create(['ci'=>' ','name'=>'HUGO SANCHEZ','address' => '']);	$cliente29=Customer::create(['person_id'=>$persona29->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona29->id,'number'=>'71896574','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona29->id,'number'=>'','type'=>'SECONDARY']);
        $persona30=Person::create(['ci'=>' ','name'=>'SUSANA LOPEZ','address' => '']);	$cliente30=Customer::create(['person_id'=>$persona30->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona30->id,'number'=>'77878779','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona30->id,'number'=>'','type'=>'SECONDARY']);
        $persona31=Person::create(['ci'=>' ','name'=>'CARLA LEMA','address' => '']);	$cliente31=Customer::create(['person_id'=>$persona31->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona31->id,'number'=>'76191717','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona31->id,'number'=>'','type'=>'SECONDARY']);
        $persona32=Person::create(['ci'=>' ','name'=>'MARIO BENITEZ','address' => '']);	$cliente32=Customer::create(['person_id'=>$persona32->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona32->id,'number'=>'72978080','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona32->id,'number'=>'','type'=>'SECONDARY']);
        $persona33=Person::create(['ci'=>' ','name'=>'JANETH OROZA','address' => '']);	$cliente33=Customer::create(['person_id'=>$persona33->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona33->id,'number'=>'70210805','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona33->id,'number'=>'','type'=>'SECONDARY']);
        $persona34=Person::create(['ci'=>' ','name'=>'MARIA DE LOS ANGELES','address' => '']);	$cliente34=Customer::create(['person_id'=>$persona34->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona34->id,'number'=>'68742111','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona34->id,'number'=>'','type'=>'SECONDARY']);
        $persona35=Person::create(['ci'=>' ','name'=>'WALTER SORUCO','address' => '']);	$cliente35=Customer::create(['person_id'=>$persona35->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona35->id,'number'=>'72943312','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona35->id,'number'=>'','type'=>'SECONDARY']);
        $persona36=Person::create(['ci'=>' ','name'=>'ALISSON SOTO','address' => '']);	$cliente36=Customer::create(['person_id'=>$persona36->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona36->id,'number'=>'77871650','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona36->id,'number'=>'','type'=>'SECONDARY']);
        $persona37=Person::create(['ci'=>' ','name'=>'DIEGO PALACIOS','address' => '']);	$cliente37=Customer::create(['person_id'=>$persona37->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona37->id,'number'=>'77871785','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona37->id,'number'=>'','type'=>'SECONDARY']);
        $persona38=Person::create(['ci'=>' ','name'=>'MERCEDES ','address' => '']);	$cliente38=Customer::create(['person_id'=>$persona38->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona38->id,'number'=>'71879710','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona38->id,'number'=>'','type'=>'SECONDARY']);
        $persona39=Person::create(['ci'=>' ','name'=>'SAMUEL ','address' => '']);	$cliente39=Customer::create(['person_id'=>$persona39->id, 'slug'=>Str::uuid(),'description'=>'','nit'=>'']);	$tel1=Telephone::create(['person_id'=>$persona39->id,'number'=>'77549797','type'=>'PRIMARY']);	$tel2=Telephone::create(['person_id'=>$persona39->id,'number'=>'','type'=>'SECONDARY']);
    }
}
